### ISSUE TITLE
Returning html?

### ISSUE THREAD

**Issue by felansu** [teamairship/react-native-public-ip#6]
when use:

```
import RNPublicIp               from "react-native-public-ip";
await RNPublicIp()
```

the return is:

`<!DOCTYPE html>	<html>	  <head>		<meta name="viewport" content="width=device-width, initial-scale=1">		<meta charset="utf-8">		<title>Application Error</title>		<style media="screen">		  html,body,iframe {			margin: 0;			padding: 0;		  }		  html,body {			height: 100%;			overflow: hidden;		  }		  iframe {			width: 100%;			height: 100%;			border: 0;		  }		</style>	  </head>	  <body>		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>	  </body>	</html>`

version: ^1.0.2

**Comment by amhinson** [comment]
Looks like the [ipify](https://www.ipify.org/) service might have been down. This library is just a basic wrapper around their API. Are you still seeing that error now?

**Comment by felansu** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/1687697/76625744-32053f00-6538-11ea-957a-98abc4424a25.png">

sometimes works sometimes no, in that example:
- 14:35: not working
- 14:33: working
- 14:32: not working

**Comment by amhinson** [comment]
Unfortunately it seems like it might be an issue with the ipify API and not this library. You can try hitting their API directly to see if that changes anything. 
https://www.ipify.org/

**Comment by felansu** [comment]
Thanks man, maybe is caused by coronavirus...
